### ISSUE TITLE
esp32 under platformio not work

### ISSUE THREAD

**Issue by chb60** [gregington/RfidDb#3]
Hi Greg, I have install your library RfidDb in platformio for my esp32 M5Stack board, I have test your example but nothing is registred, the monitor log is this :

I have add code for display memory partitions and seems eeprom is defined, I have a doubt with your first line EEPROM.put(0,0)

Thanks for your help
Regards

rst:0x1 (POWERON_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1100
load:0x40078000,len:9232
load:0x40080400,len:6412
entry 0x400806a8
M5Stack initializing...OK
Flash chip size: 4194304
Partition table:
App Partition table:
Type: 00 SubType 10 Address 0x010000 Size 0x140000 Encryption 0 Label app0
Type: 00 SubType 11 Address 0x150000 Size 0x140000 Encryption 0 Label app1
Data Partition table:
Type: 01 SubType 02 Address 0x009000 Size 0x005000 Encryption 0 Label nvs
Type: 01 SubType 00 Address 0x00E000 Size 0x002000 Encryption 0 Label otadata
Type: 01 SubType 99 Address 0x290000 Size 0x001000 Encryption 0 Label eeprom
Type: 01 SubType 82 Address 0x291000 Size 0x16F000 Encryption 0 Label spiffs
Empty database
count = 0 []
Inserting id1 = 1
count = 0 []
Contains id1 = 0
Contains id2 = 0
Contains id3 = 0
Contains id4 = 0
Contains id5 = 0
Contains (24 bit) id1 = 0
Contains (24 bit) id2 = 0
Contains (24 bit) id3 = 0
Contains (24 bit) id4 = 0
Contains (24 bit) id5 = 0
Inserting id2 = 1
count = 0 []
Contains id1 = 0
Contains id2 = 0
Contains id3 = 0
Contains id4 = 0
Contains id5 = 0
Contains (24 bit) id1 = 0
Contains (24 bit) id2 = 0
Contains (24 bit) id3 = 0
Contains (24 bit) id4 = 0
Contains (24 bit) id5 = 0
Inserting id3 = 1
count = 0 []
Contains id1 = 0
Contains id2 = 0
Contains id3 = 0
Contains id4 = 0
Contains id5 = 0
Contains (24 bit) id1 = 0
Contains (24 bit) id2 = 0
Contains (24 bit) id3 = 0
Contains (24 bit) id4 = 0
Contains (24 bit) id5 = 0
Inserting id4 = 1
count = 0 []
Contains id1 = 0
Contains id2 = 0
Contains id3 = 0
Contains id4 = 0
Contains id5 = 0
Contains (24 bit) id1 = 0
Contains (24 bit) id2 = 0
Contains (24 bit) id3 = 0
Contains (24 bit) id4 = 0
Contains (24 bit) id5 = 0
Inserting id5 = 1
count = 0 []
Contains id1 = 0
Contains id2 = 0
Contains id3 = 0
Contains id4 = 0
Contains id5 = 0
Contains (24 bit) id1 = 0
Contains (24 bit) id2 = 0
Contains (24 bit) id3 = 0
Contains (24 bit) id4 = 0
Contains (24 bit) id5 = 0
Removing id5
count = 0 []
Contains id1 = 0
Contains id2 = 0
Contains id3 = 0
Contains id4 = 0
Contains id5 = 0
Contains (24 bit) id1 = 0
Contains (24 bit) id2 = 0
Contains (24 bit) id3 = 0
Contains (24 bit) id4 = 0
Contains (24 bit) id5 = 0
Removing id1
count = 0 []
Contains id1 = 0
Contains id2 = 0
Contains id3 = 0
Contains id4 = 0
Contains id5 = 0
Contains (24 bit) id1 = 0
Contains (24 bit) id2 = 0
Contains (24 bit) id3 = 0
Contains (24 bit) id4 = 0
Contains (24 bit) id5 = 0
Removing id3
count = 0 []
Contains id1 = 0
Contains id2 = 0
Contains id3 = 0
Contains id4 = 0
Contains id5 = 0
Contains (24 bit) id1 = 0
Contains (24 bit) id2 = 0
Contains (24 bit) id3 = 0
Contains (24 bit) id4 = 0
Contains (24 bit) id5 = 0
Removing id2
count = 0 []
Contains id1 = 0
Contains id2 = 0
Contains id3 = 0
Contains id4 = 0
Contains id5 = 0
Contains (24 bit) id1 = 0
Contains (24 bit) id2 = 0
Contains (24 bit) id3 = 0
Contains (24 bit) id4 = 0
Contains (24 bit) id5 = 0
Removing id4
count = 0 []
Contains id1 = 0
Contains id2 = 0
Contains id3 = 0
Contains id4 = 0
Contains id5 = 0
Contains (24 bit) id1 = 0
Contains (24 bit) id2 = 0
Contains (24 bit) id3 = 0
Contains (24 bit) id4 = 0
Contains (24 bit) id5 = 0

**Comment by gregington** [comment]
I've never used the ESP32 platform, so I've no idea if this code works there. Can you post your test code?

I've had a quick look at ESP32 EEPROM and it seems you need to initialise in the setup() method with EEPROM.begin(EEPROM_SIZE) before reading or writing from EEPROM. Do you have such a line in your begin() method?

**Comment by gregington** [comment]
What might also be useful is a function to return the database size in bytes so that value can be passed in to EEPROM.begin(). I'll see if I can get that in the next day or two.

**Comment by gregington** [comment]
Also EEPROM writes do not commit immediately for ESP32. There's no EEPROM.commit() in the library as it was originally written for the Atmel platform. I've got some ESP8266 boards which look like they have a similar EEPROM API. I'll see if I can port this over.

**Comment by chb60** [comment]
Hi Greg,
Many thanks, it works fine now with the EEPROM.begin(0x0100)
Regards

**Comment by gregington** [comment]
I don't think it will work. Test whether the changes actually get saved to the EEPROM and are persisted across restarts. The ESP32 emulates EEPROM using its flash. Not calling EEPROM.commit() I think means that it won't get saved for the next reboot.

**Comment by gregington** [comment]
Added support for ESP32/ESP8266. Added EEPROM.commit after all EEPROM writes if on ESP8266/ESP32 platforms. 

Updated library to version 1.1.0.

Give this a try and see if it works for you.
